export const POPULATE_USER_DETAILS = "POPULATE_USER_DETAILS";
export const LOGOUT_USER = "LOGOUT_USER";
export const ADD_GIPHY_TO_FAVORITES = "ADD_GIPHY_TO_FAVORITES";
export const REMOVE_GIPHY_FROM_FAVORITES = "REMOVE_GIPHY_FROM_FAVORITES";
export const ADD_GIPHY_TAG = "ADD_GIPHY_TAG";
export const DELETE_GIPHY_TAG = "DELETE_GIPHY_TAG";
